//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfKovalev.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer
    {
        public int Id { get; set; }
        public Nullable<int> IdSystem_Unit { get; set; }
        public Nullable<int> IdProcessor { get; set; }
        public Nullable<int> IdMotherboard { get; set; }
        public Nullable<int> IdCPU_Cooling { get; set; }
        public Nullable<int> IdRAM { get; set; }
        public Nullable<int> IdStorage { get; set; }
        public Nullable<int> IdPower_Supply { get; set; }
        public Nullable<int> IdGraphics_Card { get; set; }
        public Nullable<int> IdKeyboard { get; set; }
        public Nullable<int> IdMouse { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<bool> IsPaid { get; set; }
    
        public virtual CPUCooling CPUCooling { get; set; }
        public virtual GraphicsCard GraphicsCard { get; set; }
        public virtual Keyboard Keyboard { get; set; }
        public virtual Motherboard Motherboard { get; set; }
        public virtual Mouse Mouse { get; set; }
        public virtual PowerSupply PowerSupply { get; set; }
        public virtual Processor Processor { get; set; }
        public virtual RAM RAM { get; set; }
        public virtual Storage Storage { get; set; }
        public virtual SystemUnit SystemUnit { get; set; }
        public virtual User User { get; set; }
    }
}
