//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfKovalev.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KovalevEntities : DbContext
    {
        public KovalevEntities()
            : base("name=KovalevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Computer> Computer { get; set; }
        public DbSet<CPUCooling> CPUCooling { get; set; }
        public DbSet<GraphicsCard> GraphicsCard { get; set; }
        public DbSet<Keyboard> Keyboard { get; set; }
        public DbSet<Message> Message { get; set; }
        public DbSet<Motherboard> Motherboard { get; set; }
        public DbSet<Mouse> Mouse { get; set; }
        public DbSet<PowerSupply> PowerSupply { get; set; }
        public DbSet<Processor> Processor { get; set; }
        public DbSet<RAM> RAM { get; set; }
        public DbSet<Storage> Storage { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<SystemUnit> SystemUnit { get; set; }
        public DbSet<User> User { get; set; }
    }
}
