//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfKovalev.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public int OrderId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<bool> IsPaid { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
    }
}
