//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfKovalev.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public int ProductId { get; set; }
        public Nullable<int> TypeProductId { get; set; }
        public string ComponentName { get; set; }
    
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        public virtual TypeProduct TypeProduct { get; set; }
    }
}
