//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfKovalev.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Message = new HashSet<Message>();
            this.Order = new HashSet<Order>();
        }
    
        public int UserID { get; set; }
        public string Login { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string DeliveryAddress { get; set; }
        public string PaymentMethod { get; set; }
    
        public virtual ICollection<Message> Message { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}
